version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
formats:
  - epub
  - pdf
  - htmlzip
sphinx:
  configuration: docs/source/conf.py
python:
  install:
    - requirements: requirements.txt