version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
formats:
  - htmlzip
  - epub
  - pdf
sphinx:
  configuration: docs/source/conf.py
python:
  install:
    - requirements: docs/source/requirements.txt