# Generated by Django 5.2.9 on 2026-05-25 15:00

import django.db.models.deletion
import django_ledger_extensions.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("django_ledger", "0029_stagedtransactionmodel_matched_transaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityTaxProfile",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tax_regime",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("small_business", "Small business exemption"),
                            ("exempt", "Tax exempt"),
                        ],
                        default="standard",
                        max_length=32,
                    ),
                ),
                (
                    "default_vat_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Default VAT rate as a decimal fraction, e.g. 0.19 for 19%.",
                        max_digits=5,
                    ),
                ),
                ("vat_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_profile",
                        to="django_ledger.entitymodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Tax Profile",
            },
        ),
        migrations.CreateModel(
            name="AccountTranslationModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("locale", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=150)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="django_ledger.accountmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Translation",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "locale"),
                        name="uniq_account_translation_locale",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemTranslationModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("locale", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=150)),
                (
                    "regional_code",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="django_ledger.itemmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Translation",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "locale"), name="uniq_item_translation_locale"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SupportingDocumentModel",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "file",
                    models.FileField(
                        max_length=512,
                        upload_to=django_ledger_extensions.models.supporting_document_upload_to,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("receipt", "Receipt"),
                            ("invoice", "Invoice"),
                            ("bank_statement", "Bank statement"),
                            ("contract", "Contract"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
                (
                    "immutable",
                    models.BooleanField(
                        default=False,
                        help_text="When set, the file cannot be replaced or deleted.",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supporting Document",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="django_ledg_content_56d58e_idx",
                    )
                ],
            },
        ),
    ]
