# Generated by Django 5.2.9 on 2026-05-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ledger_extensions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttranslationmodel",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="itemtranslationmodel",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
