# Generated by Django 4.1.3 on 2022-11-24 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitymodel',
            name='default_coa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.chartofaccountmodel', verbose_name='Default Chart of Accounts'),
        ),
    ]
