# pylint: skip-file
# Generated by Django 3.2.7 on 2021-09-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='inventory_received',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True,
                                      verbose_name='Total inventory received.'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='inventory_received_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True,
                                      verbose_name='Total value of inventory received.'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='sold_as_unit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='itemthroughmodel',
            index=models.Index(fields=['po_item_status'], name='django_ledg_po_item_edb12b_idx'),
        ),
    ]
