# Generated by Django 4.1.1 on 2022-10-21 15:14

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountmodel',
            name='swift_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='SWIFT Number'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='sales_tax_rate',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0.0), django.core.validators.MaxValueValidator(limit_value=1.0)], verbose_name='Sales Tax Rate'),
        ),
        migrations.AddField(
            model_name='vendormodel',
            name='aba_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ABA Number'),
        ),
        migrations.AddField(
            model_name='vendormodel',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='Only digits allowed')], verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='vendormodel',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings')], default='checking', max_length=10, verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='vendormodel',
            name='routing_number',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='Only digits allowed')], verbose_name='Routing Number'),
        ),
        migrations.AddField(
            model_name='vendormodel',
            name='swift_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='SWIFT Number'),
        ),
        migrations.AddField(
            model_name='vendormodel',
            name='tax_id_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tax Registration Number'),
        ),
        migrations.AlterField(
            model_name='bankaccountmodel',
            name='aba_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ABA Number'),
        ),
        migrations.AlterField(
            model_name='bankaccountmodel',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='Only digits allowed')], verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='bankaccountmodel',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings')], default='checking', max_length=10, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='bankaccountmodel',
            name='routing_number',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='Only digits allowed')], verbose_name='Routing Number'),
        ),
    ]
