# Generated by Django 4.1.1 on 2022-10-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entityunitmodel',
            unique_together={('entity', 'document_prefix'), ('entity', 'slug')},
        ),
    ]
