# Generated by Django 3.0.8 on 2020-07-09 02:20

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccountmodel',
            options={'verbose_name': 'Bank Account'},
        ),
        migrations.AlterField(
            model_name='bankaccountmodel',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='Only digits allowed.')]),
        ),
        migrations.AlterField(
            model_name='bankaccountmodel',
            name='routing_number',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='Only digits allowed.')]),
        ),
    ]
