# Generated by Django 3.2.14 on 2022-08-14 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseordermodel',
            name='po_date',
        ),
    ]
