# Generated by Django 3.2.7 on 2021-10-04 11:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0002_auto_20210911_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='inventory_received',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=20, verbose_name='Total inventory received.'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='inventory_received_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Total value of inventory received.'),
        ),
    ]
