# Generated by Django 4.1.1 on 2022-09-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0002_entitymodel_accrual_method_alter_accountmodel_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentrymodel',
            name='activity',
            field=models.CharField(blank=True, choices=[('Operating', (('op', 'Operating'),)), ('Investing', (('inv_ppe', 'Purchase/Disposition of PPE'), ('inv_securities', 'Purchase/Disposition of Securities'), ('inv', 'Investing Activity Other'))), ('Financing', (('fin_std', 'Payoff of Short Term Debt'), ('fin_ltd', 'Payoff of Long Term Debt'), ('fin_equity', 'Issuance of Common Stock, Preferred Stock or Capital Contribution'), ('fin_dividends', 'Dividends or Distributions to Shareholders'), ('fin', 'Financing Activity Other')))], editable=False, max_length=20, null=True, verbose_name='Activity'),
        ),
    ]
