# Generated by Django 4.1.2 on 2022-10-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0002_bankaccountmodel_swift_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customermodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vendormodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='customer_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='item_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='vendormodel',
            name='vendor_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customermodel',
            unique_together={('entity', 'customer_number')},
        ),
        migrations.AlterUniqueTogether(
            name='itemmodel',
            unique_together={('entity', 'item_number')},
        ),
        migrations.AlterUniqueTogether(
            name='vendormodel',
            unique_together={('entity', 'vendor_number')},
        ),
    ]
