# Generated by Django 3.2.1 on 2021-05-26 23:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0002_entitymodel_fy_start_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderItemThroughModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('unit_cost', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost Per Unit')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Amount QTY x UnitCost')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_ledger.entityunitmodel', verbose_name='Associated Entity Unit')),
                ('item_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ledger.itemmodel', verbose_name='Item Model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.SlugField(max_length=20, unique=True, verbose_name='Purchase Order Number')),
                ('po_date', models.DateField(verbose_name='Purchase Order Date')),
                ('po_title', models.CharField(max_length=250, verbose_name='Purchase Order Title')),
                ('po_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('po_status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved')], default='draft', max_length=10)),
                ('po_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Purchase Order Amount')),
                ('for_inventory', models.BooleanField(verbose_name='Inventory Purchase?')),
                ('fulfillment_date', models.DateField(blank=True, null=True, verbose_name='Fulfillment Date')),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.ledgermodel', verbose_name='Ledger')),
                ('po_items', models.ManyToManyField(through='django_ledger.PurchaseOrderItemThroughModel', to='django_ledger.ItemModel', verbose_name='Purchase Order Items')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='purchaseorderitemthroughmodel',
            name='po_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.purchaseordermodel', verbose_name='PO Item'),
        ),
    ]
