# Generated by Django 3.1.3 on 2020-12-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0002_auto_20201010_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='city',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='country',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='state',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip Code'),
        ),
        migrations.AddField(
            model_name='entitymodel',
            name='city',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='entitymodel',
            name='country',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='entitymodel',
            name='state',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='entitymodel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip Code'),
        ),
        migrations.AddField(
            model_name='vendormodel',
            name='city',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='vendormodel',
            name='country',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='vendormodel',
            name='state',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='State/Province'),
        ),
        migrations.AddField(
            model_name='vendormodel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip Code'),
        ),
    ]
