# Generated by Django 3.2.1 on 2021-05-26 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0003_auto_20210526_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordermodel',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.vendormodel'),
        ),
    ]
