# Generated by Django 4.1.5 on 2023-02-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0004_remove_itemmodel_depth_remove_itemmodel_numchild_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='item_role',
            field=models.CharField(blank=True, choices=[('expense', 'Expense'), ('inventory', 'Inventory'), ('service', 'Service'), ('product', 'Product')], max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='itemmodel',
            index=models.Index(fields=['item_role'], name='django_ledg_item_ro_6040aa_idx'),
        ),
    ]
