# Generated by Django 3.1.4 on 2020-12-28 17:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0004_auto_20201218_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillModelItemsThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('unit_cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost Per Unit')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Amount QTY x UnitCost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceModelItemsThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('unit_cost', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cost Per Unit')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Amount QTY x UnitCost')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='SKU Code')),
                ('upc', models.CharField(blank=True, max_length=50, null=True, verbose_name='UPC Code')),
                ('item_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Internal ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Default value per unit of measure')),
                ('for_inventory', models.BooleanField(help_text='Is an item or service you sell', verbose_name='Is item for inventory')),
                ('additional_info', models.JSONField(default=dict, verbose_name='Item Additional Info')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasureModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Unit of Measure Name')),
                ('unit_abbr', models.CharField(max_length=10, verbose_name='UoM Abbreviation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='billmodel',
            name='django_ledg_created_41f19d_idx',
        ),
        migrations.RemoveIndex(
            model_name='billmodel',
            name='django_ledg_updated_f8ea81_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_created_9d66cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_updated_2bc689_idx',
        ),
        migrations.AddField(
            model_name='billmodel',
            name='additional_info',
            field=models.JSONField(default=dict, verbose_name='Bill Additional Info'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='additional_info',
            field=models.JSONField(default=dict, verbose_name='Invoice Additional Info'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='cash_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_cash_account', to='django_ledger.accountmodel', verbose_name='Cash Account'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='earnings_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_earnings_account', to='django_ledger.accountmodel', verbose_name='Earnings Account'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='payable_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_payable_account', to='django_ledger.accountmodel', verbose_name='Payable Account'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='receivable_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_receivable_account', to='django_ledger.accountmodel', verbose_name='Receivable Account'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='cash_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_cash_account', to='django_ledger.accountmodel', verbose_name='Cash Account'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.customermodel', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='earnings_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_earnings_account', to='django_ledger.accountmodel', verbose_name='Earnings Account'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='payable_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_payable_account', to='django_ledger.accountmodel', verbose_name='Payable Account'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='receivable_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_receivable_account', to='django_ledger.accountmodel', verbose_name='Receivable Account'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='account',
            field=models.ForeignKey(help_text='Account from Chart of Accounts to be associated with this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='txs', to='django_ledger.accountmodel', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Account of the transaction.', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='description',
            field=models.CharField(blank=True, help_text='A description to be included with this individual transaction', max_length=100, null=True, verbose_name='Tx Description'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='journal_entry',
            field=models.ForeignKey(help_text='Journal Entry to be associated with this transaction.', on_delete=django.db.models.deletion.CASCADE, related_name='txs', to='django_ledger.journalentrymodel', verbose_name='Journal Entry'),
        ),
        migrations.AddIndex(
            model_name='billmodel',
            index=models.Index(fields=['date'], name='django_ledg_date_6ab9b4_idx'),
        ),
        migrations.AddIndex(
            model_name='billmodel',
            index=models.Index(fields=['due_date'], name='django_ledg_due_dat_6b961b_idx'),
        ),
        migrations.AddIndex(
            model_name='billmodel',
            index=models.Index(fields=['paid'], name='django_ledg_paid_d74dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicemodel',
            index=models.Index(fields=['date'], name='django_ledg_date_10498b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicemodel',
            index=models.Index(fields=['due_date'], name='django_ledg_due_dat_5ac804_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicemodel',
            index=models.Index(fields=['paid'], name='django_ledg_paid_3e7887_idx'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='cogs_account',
            field=models.ForeignKey(blank=True, help_text='COGS account where cost will be recognized on Income Statement.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_cogs_account', to='django_ledger.accountmodel', verbose_name='COGS Account'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='earnings_account',
            field=models.ForeignKey(blank=True, help_text='COGS account where revenue will be recognized on Income Statement.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_earnings_account', to='django_ledger.accountmodel', verbose_name='Earnings Account'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='expense_account',
            field=models.ForeignKey(blank=True, help_text='Expense account where cost will be recognized on Income Statement.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_expense_account', to='django_ledger.accountmodel', verbose_name='Expense Account'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='inventory_account',
            field=models.ForeignKey(blank=True, help_text='Inventory account where cost will be capitalized.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_inventory_account', to='django_ledger.accountmodel', verbose_name='Inventory Account'),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ledger.unitofmeasuremodel', verbose_name='Unit of Measure'),
        ),
        migrations.AddField(
            model_name='invoicemodelitemsthroughmodel',
            name='invoice_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.invoicemodel', verbose_name='Invoice Model'),
        ),
        migrations.AddField(
            model_name='invoicemodelitemsthroughmodel',
            name='item_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ledger.itemmodel', verbose_name='Item Model'),
        ),
        migrations.AddField(
            model_name='billmodelitemsthroughmodel',
            name='bill_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.billmodel', verbose_name='Bill Model'),
        ),
        migrations.AddField(
            model_name='billmodelitemsthroughmodel',
            name='item_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ledger.itemmodel', verbose_name='Item Model'),
        ),
        migrations.AddField(
            model_name='billmodel',
            name='bill_items',
            field=models.ManyToManyField(through='django_ledger.BillModelItemsThroughModel', to='django_ledger.ItemModel', verbose_name='Bill Items'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='invoice_items',
            field=models.ManyToManyField(through='django_ledger.InvoiceModelItemsThroughModel', to='django_ledger.ItemModel', verbose_name='Invoice Items'),
        ),
        migrations.AddIndex(
            model_name='itemmodel',
            index=models.Index(fields=['inventory_account'], name='django_ledg_invento_dbf206_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmodel',
            index=models.Index(fields=['cogs_account'], name='django_ledg_cogs_ac_82d441_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmodel',
            index=models.Index(fields=['earnings_account'], name='django_ledg_earning_229a60_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmodel',
            index=models.Index(fields=['expense_account'], name='django_ledg_expense_f65128_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmodel',
            index=models.Index(fields=['for_inventory'], name='django_ledg_for_inv_c93303_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmodel',
            index=models.Index(fields=['is_active'], name='django_ledg_is_acti_ffc9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicemodelitemsthroughmodel',
            index=models.Index(fields=['invoice_model', 'item_model'], name='django_ledg_invoice_942718_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicemodelitemsthroughmodel',
            index=models.Index(fields=['item_model', 'invoice_model'], name='django_ledg_item_mo_7dce6e_idx'),
        ),
        migrations.AddIndex(
            model_name='billmodelitemsthroughmodel',
            index=models.Index(fields=['bill_model', 'item_model'], name='django_ledg_bill_mo_ddba83_idx'),
        ),
        migrations.AddIndex(
            model_name='billmodelitemsthroughmodel',
            index=models.Index(fields=['item_model', 'bill_model'], name='django_ledg_item_mo_5addcf_idx'),
        ),
    ]
