# pylint: skip-file
# Generated by Django 3.2.9 on 2021-11-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_ledger', '0005_alter_purchaseordermodel_po_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='invoice_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'),
                                            ('canceled', 'Canceled')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='po_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'),
                                            ('canceled', 'Canceled')], default='draft', max_length=10),
        ),
    ]
