# Generated by Django 4.1.5 on 2023-02-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0005_itemmodel_item_role'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='itemmodel',
            index=models.Index(fields=['item_role'], name='django_ledg_item_ro_6040aa_idx'),
        ),
    ]
