# Generated by Django 3.1.4 on 2021-01-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0005_auto_20210114_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='earnings_account',
            field=models.ForeignKey(blank=True, help_text='Earnings account where revenue will be recognized on Income Statement.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_earnings_account', to='django_ledger.accountmodel', verbose_name='Earnings Account'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='entity',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='django_ledger.entitymodel', verbose_name='Item Entity'),
        ),
    ]
