# Generated by Django 3.1.4 on 2021-01-18 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0005_auto_20210114_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='entity',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='django_ledger.entitymodel', verbose_name='Item Entity'),
        ),
    ]
