# Generated by Django 3.2.9 on 2021-12-05 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0007_auto_20211129_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccountmodel',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=10, message='Slug field must contain at least 10 characters.')]),
        ),
        migrations.AlterField(
            model_name='entitymodel',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=10, message='Slug field must contain at least 10 characters.')]),
        ),
    ]
