# Generated by Django 4.2.3 on 2023-08-16 01:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0007_remove_customermodel_django_ledg_custome_16f95a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymodel',
            name='last_closing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Closing Entry Date'),
        ),
        migrations.CreateModel(
            name='ClosingEntryModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('closing_date', models.DateField(verbose_name='Closing Date')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel', verbose_name='Entity Model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClosingEntryTransactionModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity', models.CharField(blank=True, choices=[('Operating', (('op', 'Operating'),)), ('Investing', (('inv_ppe', 'Purchase/Disposition of PPE'), ('inv_securities', 'Purchase/Disposition of Securities'), ('inv', 'Investing Activity Other'))), ('Financing', (('fin_std', 'Payoff of Short Term Debt'), ('fin_ltd', 'Payoff of Long Term Debt'), ('fin_equity', 'Issuance of Common Stock, Preferred Stock or Capital Contribution'), ('fin_dividends', 'Dividends or Distributions to Shareholders'), ('fin', 'Financing Activity Other')))], max_length=20, null=True, verbose_name='Activity')),
                ('balance', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Closing Entry Balance')),
                ('account_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='django_ledger.accountmodel', verbose_name='Account Model')),
                ('closing_entry_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.closingentrymodel')),
                ('unit_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='django_ledger.entityunitmodel', verbose_name='Entity Model')),
            ],
            options={
                'verbose_name': 'Closing Entry Model',
                'ordering': ['-created'],
                'abstract': False,
                'indexes': [models.Index(fields=['closing_entry_model'], name='django_ledg_closing_a7a576_idx'), models.Index(fields=['account_model'], name='django_ledg_account_5d90df_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='closingentrytransactionmodel',
            constraint=models.UniqueConstraint(fields=('closing_entry_model', 'account_model', 'unit_model', 'activity'), name='unique_closing_entry'),
        ),
        migrations.AddConstraint(
            model_name='closingentrytransactionmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('activity', None)), fields=('closing_entry_model', 'account_model', 'unit_model'), name='unique_ce_opt_1'),
        ),
        migrations.AddConstraint(
            model_name='closingentrytransactionmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('unit_model', None)), fields=('closing_entry_model', 'account_model', 'activity'), name='unique_ce_opt_2'),
        ),
        migrations.AddConstraint(
            model_name='closingentrytransactionmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('unit_model', None), ('activity', None)), fields=('closing_entry_model', 'account_model'), name='unique_ce_opt_3'),
        ),
        migrations.AddIndex(
            model_name='closingentrymodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__4a55a2_idx'),
        ),
        migrations.AddIndex(
            model_name='closingentrymodel',
            index=models.Index(fields=['closing_date'], name='django_ledg_closing_28e3bb_idx'),
        ),
        migrations.AddIndex(
            model_name='closingentrymodel',
            index=models.Index(fields=['entity_model', 'closing_date'], name='django_ledg_entity__c306f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='closingentrymodel',
            constraint=models.UniqueConstraint(fields=('entity_model', 'closing_date'), name='unique_entity_closing_date', violation_error_message='Only one Closing Entry for Date Allowed.'),
        ),
    ]
