# Generated by Django 4.2.1 on 2023-07-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0007_remove_customermodel_django_ledg_custome_16f95a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymodel',
            name='last_closing',
            field=models.DateField(blank=True, null=True, verbose_name='Last date when books where closed.'),
        ),
    ]
