# Generated by Django 4.2.3 on 2023-07-28 16:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0007_remove_customermodel_django_ledg_custome_16f95a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosingEntryModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.SmallIntegerField(verbose_name='Fiscal Year')),
                ('fiscal_month', models.SmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True, verbose_name='Fiscal Month')),
                ('activity', models.CharField(blank=True, choices=[('Operating', (('op', 'Operating'),)), ('Investing', (('inv_ppe', 'Purchase/Disposition of PPE'), ('inv_securities', 'Purchase/Disposition of Securities'), ('inv', 'Investing Activity Other'))), ('Financing', (('fin_std', 'Payoff of Short Term Debt'), ('fin_ltd', 'Payoff of Long Term Debt'), ('fin_equity', 'Issuance of Common Stock, Preferred Stock or Capital Contribution'), ('fin_dividends', 'Dividends or Distributions to Shareholders'), ('fin', 'Financing Activity Other')))], max_length=20, null=True, verbose_name='Activity')),
                ('balance', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Closing Entry Balance')),
                ('account_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='django_ledger.accountmodel', verbose_name='Account Model')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel', verbose_name='Entity Model')),
                ('unit_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='django_ledger.entityunitmodel', verbose_name='Entity Model')),
            ],
            options={
                'verbose_name': 'Closing Entry Model',
                'ordering': ['-created'],
                'abstract': False,
                'indexes': [models.Index(fields=['entity_model'], name='django_ledg_entity__4a55a2_idx'), models.Index(fields=['account_model'], name='django_ledg_account_1a59c0_idx'), models.Index(fields=['entity_model', 'account_model', 'unit_model', 'activity', 'fiscal_year', 'fiscal_month'], name='django_ledg_entity__fa76c6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='closingentrymodel',
            constraint=models.UniqueConstraint(fields=('entity_model', 'account_model', 'fiscal_year', 'unit_model', 'fiscal_month', 'activity'), name='unique_ce_all'),
        ),
        migrations.AddConstraint(
            model_name='closingentrymodel',
            constraint=models.UniqueConstraint(condition=models.Q(('unit_model', None), ('fiscal_month', None), ('activity', None)), fields=('entity_model', 'account_model', 'fiscal_year'), name='unique_ce_opt_1'),
        ),
        migrations.AddConstraint(
            model_name='closingentrymodel',
            constraint=models.UniqueConstraint(condition=models.Q(('fiscal_month', None), ('activity', None)), fields=('entity_model', 'account_model', 'fiscal_year', 'unit_model'), name='unique_ce_opt_2'),
        ),
        migrations.AddConstraint(
            model_name='closingentrymodel',
            constraint=models.UniqueConstraint(condition=models.Q(('unit_model', None), ('activity', None)), fields=('entity_model', 'account_model', 'fiscal_year', 'fiscal_month'), name='unique_ce_opt_3'),
        ),
        migrations.AddConstraint(
            model_name='closingentrymodel',
            constraint=models.UniqueConstraint(condition=models.Q(('unit_model', None), ('fiscal_month', None)), fields=('entity_model', 'account_model', 'fiscal_year', 'activity'), name='unique_ce_opt_4'),
        ),
        migrations.AddConstraint(
            model_name='closingentrymodel',
            constraint=models.UniqueConstraint(condition=models.Q(('activity', None)), fields=('entity_model', 'account_model', 'fiscal_year', 'unit_model', 'fiscal_month'), name='unique_ce_opt_5'),
        ),
        migrations.AddConstraint(
            model_name='closingentrymodel',
            constraint=models.UniqueConstraint(condition=models.Q(('fiscal_month', None)), fields=('entity_model', 'account_model', 'fiscal_year', 'unit_model', 'activity'), name='unique_ce_opt_6'),
        ),
        migrations.AddConstraint(
            model_name='closingentrymodel',
            constraint=models.UniqueConstraint(condition=models.Q(('unit_model', None)), fields=('entity_model', 'account_model', 'fiscal_year', 'fiscal_month', 'activity'), name='unique_ce_opt_7'),
        ),
    ]
