# Generated by Django 4.2.3 on 2023-08-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0008_entitymodel_last_closing_date_closingentrymodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closingentrymodel',
            options={'ordering': ['closing_date']},
        ),
        migrations.AddField(
            model_name='entitymodel',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
