# Generated by Django 4.0.3 on 2022-04-01 00:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_ledger.models.customer_estimate
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0008_auto_20211204_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEstimateModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('markdown_notes', models.TextField(blank=True, null=True, verbose_name='Markdown Notes')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimate_number', models.SlugField(default=django_ledger.models.customer_estimate.generate_estimate_number, max_length=20, verbose_name='Estimate Number')),
                ('terms', models.CharField(choices=[('fixed', 'Fixed Price'), ('target', 'Target Price'), ('t&m', 'Time & Materials'), ('other', 'Other')], max_length=10, verbose_name='Contract Terms')),
                ('title', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='PO Title length must be greater than 5')], verbose_name='Customer Estimate Title')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='draft', max_length=10, verbose_name='Customer Estimate Status')),
                ('date_approved', models.DateField(blank=True, null=True, verbose_name='Date Approved')),
                ('date_completed', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('date_canceled', models.DateField(blank=True, null=True, verbose_name='Date Canceled')),
                ('revenue_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated cost to complete the quoted work.', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total revenue estimate')),
                ('labor_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated labor cost to complete the quoted work.', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Labor Cost of labor estimate')),
                ('material_estimate', models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated material cost to complete the quoted work.', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Material Cost Estimate')),
                ('equipment_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated equipment cost to complete the quoted work.', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Equipment Cost Estimate')),
                ('other_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated equipment cost to complete the quoted work.', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Other Cost Estimate')),
            ],
            options={
                'verbose_name': 'Customer Job',
                'verbose_name_plural': 'Customer Jobs',
                'ordering': ['-updated'],
            },
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='item_type',
            field=models.CharField(blank=True, choices=[('L', 'Labor'), ('M', 'Material'), ('E', 'Equipment')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='itemthroughmodel',
            name='ce_revenue_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total customer estimate revenue.'),
        ),
        migrations.AddField(
            model_name='itemthroughmodel',
            name='ce_unit_revenue_estimate',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Customer Estimate Revenue per Unit.'),
        ),
        migrations.AddField(
            model_name='itemthroughmodel',
            name='ce_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='django_ledger.customerestimatemodel', verbose_name='Customer Estimate'),
        ),
        migrations.AddIndex(
            model_name='itemmodel',
            index=models.Index(fields=['item_type'], name='django_ledg_item_ty_0cef58_idx'),
        ),
        migrations.AddIndex(
            model_name='itemthroughmodel',
            index=models.Index(fields=['ce_model', 'item_model'], name='django_ledg_ce_mode_3eb7c2_idx'),
        ),
        migrations.AddField(
            model_name='customerestimatemodel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ledger.customermodel', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='customerestimatemodel',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel', verbose_name='Entity Model'),
        ),
        migrations.AddIndex(
            model_name='customerestimatemodel',
            index=models.Index(fields=['status'], name='django_ledg_status_3c98b8_idx'),
        ),
        migrations.AddIndex(
            model_name='customerestimatemodel',
            index=models.Index(fields=['date_approved'], name='django_ledg_date_ap_01f2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='customerestimatemodel',
            index=models.Index(fields=['date_completed'], name='django_ledg_date_co_092c43_idx'),
        ),
        migrations.AddIndex(
            model_name='customerestimatemodel',
            index=models.Index(fields=['entity', 'estimate_number'], name='django_ledg_entity__3090a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerestimatemodel',
            unique_together={('entity', 'estimate_number')},
        ),
    ]
