# Generated by Django 4.2.2 on 2023-08-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0008_entitymodel_last_closing_date_entitymodel_meta_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='closingentrymodel',
            name='django_ledg_entity__c306f4_idx',
        ),
        migrations.AddField(
            model_name='closingentrymodel',
            name='posted',
            field=models.BooleanField(default=False, verbose_name='Is Posted'),
        ),
        migrations.AddIndex(
            model_name='closingentrymodel',
            index=models.Index(fields=['posted'], name='django_ledg_posted_8db18b_idx'),
        ),
        migrations.AddIndex(
            model_name='closingentrymodel',
            index=models.Index(fields=['entity_model', 'posted', 'closing_date'], name='django_ledg_entity__9ee361_idx'),
        ),
    ]
