# Generated by Django 4.2.1 on 2023-07-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0008_entitymodel_last_closing'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymodel',
            name='closing_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
