# Generated by Django 4.2.2 on 2023-09-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0008_closingentrymodel_closingentrytransactionmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StagedTransactionModel',
        ),
    ]
