# Generated by Django 4.2.2 on 2023-09-06 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0008_closingentrymodel_closingentrytransactionmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='journal_entry',
            field=models.ForeignKey(editable=False, help_text='Journal Entry to be associated with this transaction.', on_delete=django.db.models.deletion.CASCADE, to='django_ledger.journalentrymodel', verbose_name='Journal Entry'),
        ),
    ]
