# Generated by Django 4.2.1 on 2023-07-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0009_entitymodel_closing_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitymodel',
            old_name='last_closing',
            new_name='closing_date',
        ),
    ]
