# Generated by Django 4.0.4 on 2022-05-18 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0009_customerestimatemodel_itemmodel_item_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerEstimateModel',
            new_name='EstimateModel',
        ),
        migrations.RemoveIndex(
            model_name='estimatemodel',
            name='django_ledg_status_3c98b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='estimatemodel',
            name='django_ledg_date_ap_01f2ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='estimatemodel',
            name='django_ledg_date_co_092c43_idx',
        ),
        migrations.RemoveIndex(
            model_name='estimatemodel',
            name='django_ledg_entity__3090a8_idx',
        ),
        migrations.RemoveField(
            model_name='purchaseordermodel',
            name='fulfilled',
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='accrue',
            field=models.BooleanField(default=False, verbose_name='Accrue'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Bill Additional Info'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='amount_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Earned'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='amount_receivable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Receivable'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='amount_unearned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Unearned'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='bill_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('void', 'Void')], default='draft', max_length=10, verbose_name='Bill Status'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='accrue',
            field=models.BooleanField(default=False, verbose_name='Accrue'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Invoice Additional Info'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='amount_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Earned'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='amount_receivable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Receivable'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='amount_unearned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Unearned'),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='po_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Order Date'),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='po_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('canceled', 'Canceled'), ('fulfilled', 'Fulfilled')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='vendor_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='customermodel',
            unique_together={('entity', 'customer_name')},
        ),
        migrations.AlterUniqueTogether(
            name='vendormodel',
            unique_together={('entity', 'vendor_name')},
        ),
        migrations.AddIndex(
            model_name='estimatemodel',
            index=models.Index(fields=['status'], name='django_ledg_status_6aa955_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatemodel',
            index=models.Index(fields=['date_approved'], name='django_ledg_date_ap_a754e5_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatemodel',
            index=models.Index(fields=['date_completed'], name='django_ledg_date_co_8c0f34_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatemodel',
            index=models.Index(fields=['entity', 'estimate_number'], name='django_ledg_entity__79bf74_idx'),
        ),
    ]
