# Generated by Django 4.2.3 on 2023-09-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0009_alter_transactionmodel_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgermodel',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
