# Generated by Django 4.2.2 on 2023-08-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0009_remove_closingentrymodel_django_ledg_entity__c306f4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='closingentrymodel',
            name='markdown_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Markdown Notes'),
        ),
    ]
