# Generated by Django 4.0.4 on 2022-05-25 21:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_ledger.models.estimate
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0009_customerestimatemodel_itemmodel_item_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('markdown_notes', models.TextField(blank=True, null=True, verbose_name='Markdown Notes')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimate_number', models.SlugField(default=django_ledger.models.estimate.generate_estimate_number, max_length=20, verbose_name='Estimate Number')),
                ('terms', models.CharField(choices=[('fixed', 'Fixed Price'), ('target', 'Target Price'), ('t&m', 'Time & Materials'), ('other', 'Other')], max_length=10, verbose_name='Contract Terms')),
                ('title', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='PO Title length must be greater than 5')], verbose_name='Customer Estimate Title')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('void', 'Void'), ('canceled', 'Canceled')], default='draft', max_length=10, verbose_name='Customer Estimate Status')),
                ('date_draft', models.DateField(blank=True, null=True, verbose_name='Date Draft')),
                ('date_in_review', models.DateField(blank=True, null=True, verbose_name='Date In Review')),
                ('date_approved', models.DateField(blank=True, null=True, verbose_name='Date Approved')),
                ('date_completed', models.DateField(blank=True, null=True, verbose_name='Date Completed')),
                ('date_canceled', models.DateField(blank=True, null=True, verbose_name='Date Canceled')),
                ('date_void', models.DateField(blank=True, null=True, verbose_name='Date Void')),
                ('revenue_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated cost to complete the quoted work.', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total revenue estimate')),
                ('labor_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated labor cost to complete the quoted work.', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Labor Cost of labor estimate')),
                ('material_estimate', models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated material cost to complete the quoted work.', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Material Cost Estimate')),
                ('equipment_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated equipment cost to complete the quoted work.', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Equipment Cost Estimate')),
                ('other_estimate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated equipment cost to complete the quoted work.', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Other Cost Estimate')),
            ],
            options={
                'verbose_name': 'Customer Job',
                'verbose_name_plural': 'Customer Jobs',
                'ordering': ['-updated'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='customerestimatemodel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customerestimatemodel',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerestimatemodel',
            name='entity',
        ),
        migrations.RemoveIndex(
            model_name='billmodel',
            name='django_ledg_date_6ab9b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='billmodel',
            name='django_ledg_paid_d74dbd_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_date_10498b_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_paid_3e7887_idx',
        ),
        migrations.RemoveField(
            model_name='billmodel',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='billmodel',
            name='void',
        ),
        migrations.RemoveField(
            model_name='invoicemodel',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='invoicemodel',
            name='void',
        ),
        migrations.AddField(
            model_name='billmodel',
            name='approved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Approved Date'),
        ),
        migrations.AddField(
            model_name='billmodel',
            name='canceled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Canceled Date'),
        ),
        migrations.AddField(
            model_name='billmodel',
            name='draft_date',
            field=models.DateField(blank=True, null=True, verbose_name='Draft Date'),
        ),
        migrations.AddField(
            model_name='billmodel',
            name='in_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='In Review Date'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='approved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Approved Date'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='canceled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Canceled Date'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='draft_date',
            field=models.DateField(blank=True, null=True, verbose_name='Draft Date'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='in_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='In Review Date'),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='approved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Approved Date'),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='canceled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Canceled Date'),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='draft_date',
            field=models.DateField(blank=True, null=True, verbose_name='Draft Date'),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='in_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='In Review Date'),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='void_date',
            field=models.DateField(blank=True, null=True, verbose_name='Void Date'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='accrue',
            field=models.BooleanField(default=False, verbose_name='Accrue'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Bill Additional Info'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='amount_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Earned'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='amount_receivable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Receivable'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='amount_unearned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Unearned'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='bill_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('void', 'Void')], default='draft', max_length=10, verbose_name='Bill Status'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='accrue',
            field=models.BooleanField(default=False, verbose_name='Accrue'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Invoice Additional Info'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='amount_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Earned'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Paid'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='amount_receivable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Receivable'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='amount_unearned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(limit_value=0)], verbose_name='Amount Unearned'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='invoice_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('paid', 'Paid'), ('void', 'Void'), ('canceled', 'Canceled')], default='draft', max_length=10, verbose_name='Invoice Status'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Item Additional Info'),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='po_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Order Date'),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='po_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled'), ('void', 'Void')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='vendor_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='customermodel',
            unique_together={('entity', 'customer_name')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseordermodel',
            unique_together={('entity', 'po_number')},
        ),
        migrations.AlterUniqueTogether(
            name='vendormodel',
            unique_together={('entity', 'vendor_name')},
        ),
        migrations.AddIndex(
            model_name='billmodel',
            index=models.Index(fields=['bill_status'], name='django_ledg_bill_st_9e158c_idx'),
        ),
        migrations.AddIndex(
            model_name='billmodel',
            index=models.Index(fields=['terms'], name='django_ledg_terms_752251_idx'),
        ),
        migrations.AddIndex(
            model_name='billmodel',
            index=models.Index(fields=['draft_date'], name='django_ledg_draft_d_332311_idx'),
        ),
        migrations.AddIndex(
            model_name='billmodel',
            index=models.Index(fields=['in_review_date'], name='django_ledg_in_revi_14c4a7_idx'),
        ),
        migrations.AddIndex(
            model_name='billmodel',
            index=models.Index(fields=['approved_date'], name='django_ledg_approve_de1cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='billmodel',
            index=models.Index(fields=['paid_date'], name='django_ledg_paid_da_17b832_idx'),
        ),
        migrations.AddIndex(
            model_name='billmodel',
            index=models.Index(fields=['canceled_date'], name='django_ledg_cancele_4ea9d6_idx'),
        ),
        migrations.AddIndex(
            model_name='billmodel',
            index=models.Index(fields=['void_date'], name='django_ledg_void_da_b56e28_idx'),
        ),
        migrations.AddIndex(
            model_name='billmodel',
            index=models.Index(fields=['vendor'], name='django_ledg_vendor__28be85_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicemodel',
            index=models.Index(fields=['invoice_status'], name='django_ledg_invoice_e349d0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicemodel',
            index=models.Index(fields=['terms'], name='django_ledg_terms_3b6577_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicemodel',
            index=models.Index(fields=['customer'], name='django_ledg_custome_34c881_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicemodel',
            index=models.Index(fields=['draft_date'], name='django_ledg_draft_d_7149c6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicemodel',
            index=models.Index(fields=['in_review_date'], name='django_ledg_in_revi_6e86fd_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicemodel',
            index=models.Index(fields=['approved_date'], name='django_ledg_approve_d45d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicemodel',
            index=models.Index(fields=['paid_date'], name='django_ledg_paid_da_23fe70_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicemodel',
            index=models.Index(fields=['void_date'], name='django_ledg_void_da_859690_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicemodel',
            index=models.Index(fields=['canceled_date'], name='django_ledg_cancele_e1f891_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseordermodel',
            index=models.Index(fields=['entity'], name='django_ledg_entity__9ab6ba_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseordermodel',
            index=models.Index(fields=['po_status'], name='django_ledg_po_stat_ab8d41_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseordermodel',
            index=models.Index(fields=['ce_model'], name='django_ledg_ce_mode_66c2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseordermodel',
            index=models.Index(fields=['draft_date'], name='django_ledg_draft_d_e2ead8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseordermodel',
            index=models.Index(fields=['in_review_date'], name='django_ledg_in_revi_5a0711_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseordermodel',
            index=models.Index(fields=['approved_date'], name='django_ledg_approve_88d2df_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseordermodel',
            index=models.Index(fields=['fulfillment_date'], name='django_ledg_fulfill_a26afe_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseordermodel',
            index=models.Index(fields=['canceled_date'], name='django_ledg_cancele_22ec28_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseordermodel',
            index=models.Index(fields=['void_date'], name='django_ledg_void_da_b2109f_idx'),
        ),
        migrations.AddField(
            model_name='estimatemodel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='django_ledger.customermodel', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='estimatemodel',
            name='entity',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel', verbose_name='Entity Model'),
        ),
        migrations.RemoveField(
            model_name='purchaseordermodel',
            name='fulfilled',
        ),
        migrations.AlterField(
            model_name='itemthroughmodel',
            name='ce_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.estimatemodel', verbose_name='Customer Estimate'),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='ce_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='django_ledger.estimatemodel', verbose_name='Associated Customer Job/Estimate'),
        ),
        migrations.DeleteModel(
            name='CustomerEstimateModel',
        ),
        migrations.AddIndex(
            model_name='estimatemodel',
            index=models.Index(fields=['status'], name='django_ledg_status_6aa955_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatemodel',
            index=models.Index(fields=['customer'], name='django_ledg_custome_a2793e_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatemodel',
            index=models.Index(fields=['terms'], name='django_ledg_terms_9507f6_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatemodel',
            index=models.Index(fields=['entity'], name='django_ledg_entity__e2e967_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatemodel',
            index=models.Index(fields=['date_draft'], name='django_ledg_date_dr_502e29_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatemodel',
            index=models.Index(fields=['date_in_review'], name='django_ledg_date_in_b24ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatemodel',
            index=models.Index(fields=['date_approved'], name='django_ledg_date_ap_a754e5_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatemodel',
            index=models.Index(fields=['date_canceled'], name='django_ledg_date_ca_9af3db_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatemodel',
            index=models.Index(fields=['date_void'], name='django_ledg_date_vo_74c7c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='estimatemodel',
            unique_together={('entity', 'estimate_number')},
        ),
    ]
