# Generated by Django 4.0.4 on 2022-05-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0009_customerestimatemodel_itemmodel_item_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerEstimateModel',
            new_name='EstimateModel',
        ),
        migrations.RemoveIndex(
            model_name='estimatemodel',
            name='django_ledg_status_3c98b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='estimatemodel',
            name='django_ledg_date_ap_01f2ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='estimatemodel',
            name='django_ledg_date_co_092c43_idx',
        ),
        migrations.RemoveIndex(
            model_name='estimatemodel',
            name='django_ledg_entity__3090a8_idx',
        ),
        migrations.AddIndex(
            model_name='estimatemodel',
            index=models.Index(fields=['status'], name='django_ledg_status_6aa955_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatemodel',
            index=models.Index(fields=['date_approved'], name='django_ledg_date_ap_a754e5_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatemodel',
            index=models.Index(fields=['date_completed'], name='django_ledg_date_co_8c0f34_idx'),
        ),
        migrations.AddIndex(
            model_name='estimatemodel',
            index=models.Index(fields=['entity', 'estimate_number'], name='django_ledg_entity__79bf74_idx'),
        ),
    ]
