# Generated by Django 3.2.13 on 2022-06-19 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0010_estimatemodel_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entitymodel',
            name='django_ledg_parent__0c1f50_idx',
        ),
        migrations.RemoveField(
            model_name='entitymodel',
            name='parent',
        ),
        migrations.AddField(
            model_name='billmodel',
            name='ce_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='django_ledger.estimatemodel', verbose_name='Associated Customer Job/Estimate'),
        ),
        migrations.AddField(
            model_name='entitymodel',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entitymodel',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entitymodel',
            name='path',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='ce_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='django_ledger.estimatemodel', verbose_name='Associated Customer Job/Estimate'),
        ),
    ]
