# Generated by Django 4.2.2 on 2023-08-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0010_closingentrymodel_markdown_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closingentrymodel',
            options={'ordering': ['-closing_date']},
        ),
        migrations.AddField(
            model_name='journalentrymodel',
            name='is_closing_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='journalentrymodel',
            index=models.Index(fields=['is_closing_entry'], name='django_ledg_is_clos_0ef09e_idx'),
        ),
    ]
