# Generated by Django 4.0.4 on 2022-05-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0010_rename_customerestimatemodel_estimatemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='po_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Order Date'),
        ),
    ]
