# Generated by Django 4.2.1 on 2023-07-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0010_rename_last_closing_entitymodel_closing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitymodel',
            name='closing_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Closing Data'),
        ),
    ]
