# Generated by Django 4.0.4 on 2022-05-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0010_rename_customerestimatemodel_estimatemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billmodel',
            name='approved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Approved Date'),
        ),
        migrations.AddField(
            model_name='billmodel',
            name='canceled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Canceled Date'),
        ),
        migrations.AddField(
            model_name='billmodel',
            name='in_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='In Review Date'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='approved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Approved Date'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='canceled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Canceled Date'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='in_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='In Review Date'),
        ),
        migrations.AlterField(
            model_name='estimatemodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('completed', 'Void'), ('canceled', 'Canceled')], default='draft', max_length=10, verbose_name='Customer Estimate Status'),
        ),
    ]
