# Generated by Django 4.2.2 on 2023-09-25 14:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0010_delete_importjobmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJobModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('completed', models.BooleanField(default=False, verbose_name='Import Job Completed')),
                ('bank_account_model', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='django_ledger.bankaccountmodel', verbose_name='Associated Bank Account Model')),
                ('ledger_model', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_ledger.ledgermodel', verbose_name='Ledger Model')),
            ],
            options={
                'verbose_name': 'Import Job Model',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StagedTransactionModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fit_id', models.CharField(max_length=100)),
                ('date_posted', models.DateField(verbose_name='Date Posted')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('memo', models.CharField(blank=True, max_length=200, null=True)),
                ('account_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_ledger.accountmodel')),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.importjobmodel')),
                ('transaction_model', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_ledger.transactionmodel')),
            ],
            options={
                'verbose_name': 'Staged Transaction Model',
                'abstract': False,
                'indexes': [models.Index(fields=['import_job'], name='django_ledg_import__8e6511_idx'), models.Index(fields=['date_posted'], name='django_ledg_date_po_cbcc8c_idx'), models.Index(fields=['account_model'], name='django_ledg_account_53aea9_idx'), models.Index(fields=['transaction_model'], name='django_ledg_transac_51a6b9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='importjobmodel',
            index=models.Index(fields=['bank_account_model'], name='django_ledg_bank_ac_0bad20_idx'),
        ),
        migrations.AddIndex(
            model_name='importjobmodel',
            index=models.Index(fields=['ledger_model'], name='django_ledg_ledger__d9e03f_idx'),
        ),
        migrations.AddIndex(
            model_name='importjobmodel',
            index=models.Index(fields=['completed'], name='django_ledg_complet_42632b_idx'),
        ),
    ]
