# Generated by Django 4.0.4 on 2022-05-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0010_rename_customerestimatemodel_estimatemodel_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='billmodel',
            name='django_ledg_paid_d74dbd_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_paid_3e7887_idx',
        ),
        migrations.RemoveField(
            model_name='billmodel',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='billmodel',
            name='void',
        ),
        migrations.RemoveField(
            model_name='invoicemodel',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='invoicemodel',
            name='void',
        ),
        migrations.AddIndex(
            model_name='billmodel',
            index=models.Index(fields=['bill_status'], name='django_ledg_bill_st_9e158c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicemodel',
            index=models.Index(fields=['invoice_status'], name='django_ledg_invoice_e349d0_idx'),
        ),
    ]
