# Generated by Django 4.0.4 on 2022-05-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0011_alter_purchaseordermodel_po_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='po_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('canceled', 'Canceled'), ('fulfilled', 'Fulfilled')], default='draft', max_length=10),
        ),
    ]
