# Generated by Django 4.0.4 on 2022-05-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0011_billmodel_approved_date_billmodel_canceled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billmodel',
            name='draft_date',
            field=models.DateField(blank=True, null=True, verbose_name='Draft Date'),
        ),
        migrations.AddField(
            model_name='estimatemodel',
            name='date_draft',
            field=models.DateField(blank=True, null=True, verbose_name='Date Draft'),
        ),
        migrations.AddField(
            model_name='estimatemodel',
            name='date_in_review',
            field=models.DateField(blank=True, null=True, verbose_name='Date In Review'),
        ),
        migrations.AddField(
            model_name='estimatemodel',
            name='date_void',
            field=models.DateField(blank=True, null=True, verbose_name='Date Void'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='draft_date',
            field=models.DateField(blank=True, null=True, verbose_name='Draft Date'),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='approved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Approved Date'),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='canceled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Canceled Date'),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='draft_date',
            field=models.DateField(blank=True, null=True, verbose_name='Draft Date'),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='in_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='In Review Date'),
        ),
        migrations.AlterField(
            model_name='estimatemodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('void', 'Void'), ('canceled', 'Canceled')], default='draft', max_length=10, verbose_name='Customer Estimate Status'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='additional_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Item Additional Info'),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='po_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled'), ('void', 'Void')], default='draft', max_length=10),
        ),
    ]
