# Generated by Django 4.2.1 on 2023-07-21 15:03

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0011_alter_entitymodel_closing_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitymodel',
            name='closing_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Closing Data'),
        ),
    ]
