# Generated by Django 4.2.3 on 2023-09-25 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0011_importjobmodel_stagedtransactionmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedtransactionmodel',
            name='amount_split',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='stagedtransactionmodel',
            name='parent',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_transaction_set', to='django_ledger.stagedtransactionmodel', verbose_name='Parent Transaction'),
        ),
    ]
