# Generated by Django 4.2.3 on 2023-09-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0011_importjobmodel_stagedtransactionmodel_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='importjobmodel',
            index=models.Index(fields=['ledger_model'], name='django_ledg_ledger__d9e03f_idx'),
        ),
    ]
