# Generated by Django 4.0.4 on 2022-05-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0013_alter_purchaseordermodel_po_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordermodel',
            name='void_date',
            field=models.DateField(blank=True, null=True, verbose_name='Void Date'),
        ),
    ]
