# Generated by Django 5.1.2 on 2024-12-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0018_transactionmodel_cleared_transactionmodel_reconciled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invoicemodel',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='customermodel',
            name='django_ledg_created_ba7f4c_idx',
        ),
        migrations.RemoveIndex(
            model_name='customermodel',
            name='django_ledg_updated_f9ac90_idx',
        ),
        migrations.RemoveIndex(
            model_name='customermodel',
            name='django_ledg_active_967a81_idx',
        ),
        migrations.RemoveIndex(
            model_name='customermodel',
            name='django_ledg_hidden_dda722_idx',
        ),
        migrations.RemoveIndex(
            model_name='customermodel',
            name='django_ledg_entity__7b3ad8_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_invoice_e349d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_terms_3b6577_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_cash_ac_00d697_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_prepaid_470f67_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_unearne_bc18fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_date_du_c72892_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_date_dr_ad2569_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_date_in_e738b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_date_ap_ae90e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_date_pa_34b872_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_date_ca_0f65e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_date_vo_57c444_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_custome_34c881_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicemodel',
            name='django_ledg_invoice_d0881e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='customermodel',
            unique_together=set(),
        ),
    ]
