# Generated by Django 5.2.1 on 2025-06-24 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ledger', '0021_alter_bankaccountmodel_account_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountmodel',
            name='bank_account_type',
            field=models.CharField(blank=True, help_text='Type of bank account. Eg: Savings, Checking, Credit Card', max_length=150, null=True, verbose_name='Bank Account Type'),
        ),
        migrations.AlterField(
            model_name='bankaccountmodel',
            name='account_model',
            field=models.OneToOneField(help_text='Account model be used to map transactions from financial institution', on_delete=django.db.models.deletion.RESTRICT, to='django_ledger.accountmodel', verbose_name='Associated Account Model'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='bill_items',
            field=models.ManyToManyField(through='django_ledger.ItemTransactionModel', through_fields=('bill_model', 'item_model'), to='django_ledger.itemmodel', verbose_name='Bill Items'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='invoice_items',
            field=models.ManyToManyField(through='django_ledger.ItemTransactionModel', through_fields=('invoice_model', 'item_model'), to='django_ledger.itemmodel', verbose_name='Invoice Items'),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='po_items',
            field=models.ManyToManyField(through='django_ledger.ItemTransactionModel', through_fields=('po_model', 'item_model'), to='django_ledger.itemmodel', verbose_name='Purchase Order Items'),
        ),
        migrations.AddIndex(
            model_name='bankaccountmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__6ad006_idx'),
        ),
    ]
