# Generated by Django 5.2.1 on 2025-06-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_ledger', '0021_alter_bankaccountmodel_account_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountmodel',
            name='account_type',
            field=models.CharField(
                choices=[('checking', 'Checking'), ('savings', 'Savings'), ('money_market', 'Money Market'),
                         ('cert_deposit', 'Certificate of Deposit'), ('credit_card', 'Credit Card'),
                         ('st_loan', 'Short Term Loan'), ('lt_loan', 'Long Term Loan'), ('mortgage', 'Mortgage'),
                         ('other', 'Other')], default='checking', max_length=20, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='billmodel',
            name='bill_items',
            field=models.ManyToManyField(through='django_ledger.ItemTransactionModel',
                                         through_fields=('bill_model', 'item_model'), to='django_ledger.itemmodel',
                                         verbose_name='Bill Items'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='invoice_items',
            field=models.ManyToManyField(through='django_ledger.ItemTransactionModel',
                                         through_fields=('invoice_model', 'item_model'), to='django_ledger.itemmodel',
                                         verbose_name='Invoice Items'),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='po_items',
            field=models.ManyToManyField(through='django_ledger.ItemTransactionModel',
                                         through_fields=('po_model', 'item_model'), to='django_ledger.itemmodel',
                                         verbose_name='Purchase Order Items'),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='account_type',
            field=models.CharField(
                choices=[('checking', 'Checking'), ('savings', 'Savings'), ('money_market', 'Money Market'),
                         ('cert_deposit', 'Certificate of Deposit'), ('credit_card', 'Credit Card'),
                         ('st_loan', 'Short Term Loan'), ('lt_loan', 'Long Term Loan'), ('mortgage', 'Mortgage'),
                         ('other', 'Other')], default='checking', max_length=20, verbose_name='Account Type'),
        ),
        migrations.AddIndex(
            model_name='bankaccountmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__6ad006_idx'),
        ),
    ]
