# Generated by Django 5.2.1 on 2025-06-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_ledger', '0021_alter_bankaccountmodel_account_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billmodel',
            name='bill_items',
            field=models.ManyToManyField(
                through='django_ledger.ItemTransactionModel',
                through_fields=('bill_model', 'item_model'), to='django_ledger.itemmodel',
                verbose_name='Bill Items'
            ),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='invoice_items',
            field=models.ManyToManyField(
                through='django_ledger.ItemTransactionModel',
                through_fields=('invoice_model', 'item_model'), to='django_ledger.itemmodel',
                verbose_name='Invoice Items'
            ),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='po_items',
            field=models.ManyToManyField(
                through='django_ledger.ItemTransactionModel',
                through_fields=('po_model', 'item_model'), to='django_ledger.itemmodel',
                verbose_name='Purchase Order Items'
            ),
        ),
    ]
