# Generated by Django 5.2.13 on 2026-04-28 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_ledger', '0024_billmodel_entity_model_invoicemodel_entity_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentrymodel',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de origen'),
        ),
        migrations.AddField(
            model_name='journalentrymodel',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='objeto'),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Tipo de origen'),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='objeto'),
        ),
        migrations.AddIndex(
            model_name='journalentrymodel',
            index=models.Index(fields=['content_type', 'object_id'], name='django_ledg_content_78b30f_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionmodel',
            index=models.Index(fields=['content_type', 'object_id'], name='django_ledg_content_a48ccf_idx'),
        ),
    ]
