# Generated by Django 6.0.6 on 2026-06-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_ledger', '0025_journalentrymodel_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='content_type_agrupador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_type_agrupador', to='contenttypes.contenttype', verbose_name='Tipo de origen del agrupador'),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='object_agrupador_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='objeto agrupador'),
        ),
        migrations.AddIndex(
            model_name='transactionmodel',
            index=models.Index(fields=['content_type_agrupador', 'object_agrupador_id'], name='django_ledg_content_bd4afe_idx'),
        ),
    ]
