# Generated by Django 6.0.1 on 2026-05-18 10:11

import django.core.validators
import django.db.models.deletion
import django_ledger.models.enterprise
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_ledger', '0029_stagedtransactionmodel_matched_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='billmodel',
            name='base_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='billmodel',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='base_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='journalentrymodel',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='base_po_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Base Currency Amount'),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='currency_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Currency Amount'),
        ),
        migrations.CreateModel(
            name='AccountingPeriodModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField()),
                ('period', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('soft_closed', 'Soft Closed'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='open', max_length=16)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllocationRuleModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_sources', to='django_ledger.accountmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovalPolicyModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('document_type', models.CharField(default='all', max_length=50)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('account_role', models.CharField(blank=True, max_length=30)),
                ('required_role', models.CharField(choices=[('owner', 'Owner'), ('finance_admin', 'Finance Admin'), ('accountant', 'Accountant'), ('approver', 'Approver'), ('auditor', 'Auditor'), ('read_only', 'Read Only'), ('integration', 'Integration User')], default='approver', max_length=32)),
                ('required_approvals', models.PositiveSmallIntegerField(default=1)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('entity_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_ledger.entityunitmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequestModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('reason', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.approvalpolicymodel')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovalStepModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('comment', 'Comment')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.approvalrequestmodel')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetCategoryModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('accumulated_depreciation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accumulated_depreciation_categories', to='django_ledger.accountmodel')),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_categories', to='django_ledger.accountmodel')),
                ('depreciation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_categories', to='django_ledger.accountmodel')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditEventModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('state', 'State Change'), ('approve', 'Approve'), ('post', 'Post'), ('lock', 'Lock'), ('export', 'Export'), ('import', 'Import')], max_length=20)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('request_meta', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankStatementModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_id', models.CharField(blank=True, max_length=120)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('reconciling', 'Reconciling'), ('reconciled', 'Reconciled'), ('locked', 'Locked'), ('void', 'Void')], default='imported', max_length=16)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.bankaccountmodel')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankStatementLineModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posted_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payee', models.CharField(blank=True, max_length=255)),
                ('memo', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('ignored', models.BooleanField(default=False)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_ledger.transactionmodel')),
                ('statement_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.bankstatementmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankReconciliationModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('reconciled', 'Reconciled'), ('locked', 'Locked'), ('void', 'Void')], default='draft', max_length=16)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('statement_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.bankstatementmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('fiscal_year', models.IntegerField()),
                ('status', models.CharField(default='draft', max_length=16)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetVersionModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.budgetmodel')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CloseTaskModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.accountingperiodmodel')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditNoteModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_number', models.CharField(blank=True, max_length=30)),
                ('note_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unapplied_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ledger.customermodel')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_ledger.invoicemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='billmodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.currencymodel', verbose_name='Document Currency'),
        ),
        migrations.AddField(
            model_name='entitymodel',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.currencymodel', verbose_name='Base Currency'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.currencymodel', verbose_name='Document Currency'),
        ),
        migrations.AddField(
            model_name='journalentrymodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.currencymodel', verbose_name='Transaction Currency'),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.currencymodel', verbose_name='Document Currency'),
        ),
        migrations.CreateModel(
            name='DebitNoteModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_number', models.CharField(blank=True, max_length=30)),
                ('note_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unapplied_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_ledger.billmodel')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ledger.vendormodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepreciationMethodModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('method', models.CharField(choices=[('straight_line', 'Straight Line')], default='straight_line', max_length=32)),
                ('useful_life_months', models.PositiveIntegerField()),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DimensionModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dimension_type', models.CharField(choices=[('department', 'Department'), ('project', 'Project'), ('location', 'Location'), ('cost_center', 'Cost Center'), ('product_line', 'Product Line')], max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DimensionValueModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.dimensionmodel')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DimensionAssignmentModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('weight', models.DecimalField(decimal_places=6, default=Decimal('1.00'), max_digits=9)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('dimension_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ledger.dimensionvaluemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetLineModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ledger.accountmodel')),
                ('accounting_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.accountingperiodmodel')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('entity_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.entityunitmodel')),
                ('budget_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.budgetversionmodel')),
                ('dimension_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.dimensionvaluemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllocationRuleLineModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(decimal_places=6, max_digits=9)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_targets', to='django_ledger.accountmodel')),
                ('allocation_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.allocationrulemodel')),
                ('dimension_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.dimensionvaluemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachmentModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('file', models.FileField(upload_to=django_ledger.models.enterprise.document_attachment_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=128)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('retention_date', models.DateField(blank=True, null=True)),
                ('ocr_payload', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityRoleModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('finance_admin', 'Finance Admin'), ('accountant', 'Accountant'), ('approver', 'Approver'), ('auditor', 'Auditor'), ('read_only', 'Read Only'), ('integration', 'Integration User')], max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rate_date', models.DateField()),
                ('source', models.CharField(blank=True, max_length=80)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates_from', to='django_ledger.currencymodel')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates_to', to='django_ledger.currencymodel')),
            ],
            options={
                'ordering': ['-rate_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FixedAssetModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_number', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('acquisition_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disposed', 'Disposed'), ('impaired', 'Impaired')], default='active', max_length=16)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ledger.assetcategorymodel')),
                ('depreciation_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ledger.depreciationmethodmodel')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepreciationScheduleModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('posted', models.BooleanField(default=False)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_ledger.journalentrymodel')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ledger.accountingperiodmodel')),
                ('fixed_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.fixedassetmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetDisposalModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disposal_date', models.DateField()),
                ('proceeds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('notes', models.TextField(blank=True)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_ledger.journalentrymodel')),
                ('fixed_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ledger.fixedassetmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntegrationCredentialModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('token_hash', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='draft', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentLineModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=20)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('entity_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.entityunitmodel')),
                ('item_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ledger.itemmodel')),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.inventoryadjustmentmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryValuationPolicyModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('method', models.CharField(choices=[('fifo', 'FIFO'), ('weighted_average', 'Weighted Average'), ('standard', 'Standard Cost')], max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('ar', 'Accounts Receivable'), ('ap', 'Accounts Payable')], max_length=2)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unapplied_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('base_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('posted', 'Posted'), ('void', 'Void')], default='draft', max_length=16)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.bankaccountmodel')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.currencymodel')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.customermodel')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.vendormodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocationModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('write_off_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.paymentmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxAuthorityModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('jurisdiction', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxCodeModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('tax_type', models.CharField(choices=[('output', 'Output Tax'), ('input', 'Input Tax'), ('exempt', 'Exempt'), ('zero', 'Zero Rated'), ('reverse', 'Reverse Charge'), ('withholding', 'Withholding')], max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ledger.taxauthoritymodel')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxRateModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.taxcodemodel')),
            ],
            options={
                'ordering': ['-effective_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxLineModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('inclusive', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('filing_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_ledger.accountingperiodmodel')),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_ledger.taxcodemodel')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_ledger.taxratemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpointModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('secret', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('event_types', models.JSONField(blank=True, default=list)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryModel',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('delivered', models.BooleanField(default=False)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('entity_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.entitymodel')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_ledger.webhookendpointmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='accountingperiodmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__46b67c_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiodmodel',
            index=models.Index(fields=['entity_model', 'status', 'start_date', 'end_date'], name='django_ledg_entity__663151_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountingperiodmodel',
            constraint=models.UniqueConstraint(fields=('entity_model', 'fiscal_year', 'period'), name='unique_entity_accounting_period'),
        ),
        migrations.AddIndex(
            model_name='allocationrulemodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__27b2db_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalpolicymodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__25e959_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalpolicymodel',
            index=models.Index(fields=['entity_model', 'active', 'document_type'], name='django_ledg_entity__1c0606_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequestmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__d506d9_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequestmodel',
            index=models.Index(fields=['entity_model', 'status', 'created'], name='django_ledg_entity__95c048_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalstepmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__a3a35e_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalstepmodel',
            index=models.Index(fields=['approval_request', 'action'], name='django_ledg_approva_9734b2_idx'),
        ),
        migrations.AddIndex(
            model_name='assetcategorymodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__662f81_idx'),
        ),
        migrations.AddIndex(
            model_name='auditeventmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__32b07b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditeventmodel',
            index=models.Index(fields=['entity_model', 'action', 'created'], name='django_ledg_entity__514c94_idx'),
        ),
        migrations.AddIndex(
            model_name='auditeventmodel',
            index=models.Index(fields=['correlation_id'], name='django_ledg_correla_3b33c0_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__313429_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementmodel',
            constraint=models.UniqueConstraint(fields=('entity_model', 'bank_account', 'statement_id'), name='unique_bank_statement_id'),
        ),
        migrations.AddIndex(
            model_name='bankstatementlinemodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__5690cd_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementlinemodel',
            index=models.Index(fields=['statement_model', 'posted_date'], name='django_ledg_stateme_94439a_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementlinemodel',
            index=models.Index(fields=['entity_model', 'amount', 'posted_date'], name='django_ledg_entity__69ef34_idx'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliationmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__c7745a_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__1ea486_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetmodel',
            constraint=models.UniqueConstraint(fields=('entity_model', 'name', 'fiscal_year'), name='unique_budget_year_name'),
        ),
        migrations.AddIndex(
            model_name='budgetversionmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__7e6716_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetversionmodel',
            constraint=models.UniqueConstraint(fields=('budget', 'version'), name='unique_budget_version'),
        ),
        migrations.AddIndex(
            model_name='closetaskmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__e23caf_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnotemodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__37f74f_idx'),
        ),
        migrations.AddIndex(
            model_name='debitnotemodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__4195f7_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationmethodmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__56bb8b_idx'),
        ),
        migrations.AddIndex(
            model_name='dimensionmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__22f3ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='dimensionmodel',
            constraint=models.UniqueConstraint(fields=('entity_model', 'dimension_type', 'name'), name='unique_dimension_name'),
        ),
        migrations.AddIndex(
            model_name='dimensionvaluemodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__e63ad9_idx'),
        ),
        migrations.AddConstraint(
            model_name='dimensionvaluemodel',
            constraint=models.UniqueConstraint(fields=('dimension', 'code'), name='unique_dimension_value_code'),
        ),
        migrations.AddIndex(
            model_name='dimensionassignmentmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__c88433_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetlinemodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__886fda_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationrulelinemodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__29996e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentattachmentmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__329d20_idx'),
        ),
        migrations.AddIndex(
            model_name='entityrolemodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__ee8aca_idx'),
        ),
        migrations.AddIndex(
            model_name='entityrolemodel',
            index=models.Index(fields=['user', 'role', 'active'], name='django_ledg_user_id_032501_idx'),
        ),
        migrations.AddConstraint(
            model_name='entityrolemodel',
            constraint=models.UniqueConstraint(fields=('entity_model', 'user', 'role'), name='unique_entity_user_role'),
        ),
        migrations.AddIndex(
            model_name='exchangeratemodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__91a200_idx'),
        ),
        migrations.AddConstraint(
            model_name='exchangeratemodel',
            constraint=models.UniqueConstraint(fields=('entity_model', 'from_currency', 'to_currency', 'rate_date'), name='unique_exchange_rate'),
        ),
        migrations.AddIndex(
            model_name='fixedassetmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__6f7a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='depreciationschedulemodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__c62b8b_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdisposalmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__844639_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationcredentialmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__8a3bef_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustmentmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__b67e73_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustmentlinemodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__5945db_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryvaluationpolicymodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__fd2d00_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__b77519_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmodel',
            index=models.Index(fields=['entity_model', 'direction', 'status', 'payment_date'], name='django_ledg_entity__30f268_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocationmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__4372d1_idx'),
        ),
        migrations.AddIndex(
            model_name='taxauthoritymodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__bd6b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='taxcodemodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__afa3ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxcodemodel',
            constraint=models.UniqueConstraint(fields=('entity_model', 'code'), name='unique_entity_tax_code'),
        ),
        migrations.AddIndex(
            model_name='taxratemodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__b8954b_idx'),
        ),
        migrations.AddIndex(
            model_name='taxlinemodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__28a10b_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookendpointmodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__ccc1b6_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliverymodel',
            index=models.Index(fields=['entity_model'], name='django_ledg_entity__fe73a7_idx'),
        ),
    ]
