# Generated by Django 5.2.9 on 2026-05-25 15:32

import django_ledger.models.accounts
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ledger", "0029_stagedtransactionmodel_matched_transaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountmodel",
            name="code",
            field=models.CharField(
                max_length=12,
                validators=[django_ledger.models.accounts.account_code_validator],
                verbose_name="Account Code",
            ),
        ),
        migrations.AlterField(
            model_name="accountmodel",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Account Name"),
        ),
    ]
